server:
  port: 8001
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.gof.springcloud.entities
  mapper-locations: classpath:mybatis/mapper/*.xml

logging:
  file:
    name: ./log/travel-plan-api.log
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  application:
    name: microservicecloud-travel-plan
  data:
    mongodb:
      uri: mongodb://mongo.local:27017
      database: travelplan
  redis:
    database: 0
    host: redis.local
    port: 6379
    password:
    timeout: 10000
      
eureka:
  client: #client register into eureka
    service-url: 
      defaultZone: http://eureka.local:7001/eureka/
  instance:
    instance-id: microservicecloud-travel-plan8001-hystrix
    prefer-ip-address: true
      
info:
  app.name: gof-microservicecloud
  company.name: www.gof.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
